set_property -dict [list \
	CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100}		\
  CONFIG.PCW_EN_CLK1_PORT {1} 		\
	CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {200}		\
	CONFIG.PCW_USE_S_AXI_HP0 {1}		\
	CONFIG.PCW_USE_S_AXI_HP1 {1}		\
	CONFIG.PCW_USE_FABRIC_INTERRUPT {1}		\
	CONFIG.PCW_IRQ_F2P_INTR {1}		\
	CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {1}		\
] [get_bd_cells -hierarchical -filter {VLNV=~"*processing_system7*"}]





